# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [ ]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [ ]:
np.version.version

<function numpy.info>

#### Q3 : Créer un vecteur nul de taille 10

In [ ]:
np.zeros(10).reshape((10,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [ ]:
v0 = np.zeros(10).reshape((10,1))
v0[4] = 1
v0

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [ ]:
Z = np.arange(10,51).reshape((41,1)) ; Z

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50]])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [ ]:
Z = Z[::-1] ; Z

array([[50],
       [49],
       [48],
       [47],
       [46],
       [45],
       [44],
       [43],
       [42],
       [41],
       [40],
       [39],
       [38],
       [37],
       [36],
       [35],
       [34],
       [33],
       [32],
       [31],
       [30],
       [29],
       [28],
       [27],
       [26],
       [25],
       [24],
       [23],
       [22],
       [21],
       [20],
       [19],
       [18],
       [17],
       [16],
       [15],
       [14],
       [13],
       [12],
       [11],
       [10]])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [ ]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [ ]:
np.arange(0,27).reshape((3,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [ ]:
s = np.arange(0,100).reshape((10,10))
print(np.amin(s))
print(np.amax(s))

0
99


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)