In [3]:
import numpy as np
import pandas as pds

url = 'https://bit.ly/tx-data'
df = pds.read_csv(url)

In [4]:
df

transaction_id  first_name   last_name       ip_address   amount
0       50563-403      Jacobo    Haresign    18.144.134.48  $647.77
1      54569-3911     Christy        Derl  254.107.123.242  $460.47
2      59667-0024      Florie      Prewer    148.80.11.233  $565.38
3       60429-123      Danika      Shimuk   233.91.221.158  $794.76
4       0187-0771    Annelise   Antonescu   238.143.41.105  $790.41
5       53942-299       Upton        Emig  103.190.123.125  $759.53
6       41163-519     Rachael     Housley    3.188.252.248  $871.72
7       60289-247       Corri  Rockcliffe    46.150.208.18    $5.68
8       0527-1742      Ambros    Goulding   174.124.224.39  $726.12
9       57237-083        Roma     Addekin     37.14.63.174  $526.89
10      60758-060     Auberon       Boxen     168.0.223.98  $309.65
11     43857-0289      Cesare   Andriolli    244.204.3.163  $746.23
12      68180-751      Marlon      Fernie   61.133.100.141  $974.30
13      43319-040   Gavrielle      Vittet    180.20.70.166  $994.20
14      65862-207      Alvira      Heifer   141.170.128.72  $584.13
15      68180-751      Marlon      Fernie   61.133.100.141  $974.30
16      0066-0508        Jedd     Hartman     21.55.247.91  $749.96
17      0187-5102        Beth     Lamping    125.152.40.91   $19.07
18     44887-2589      Sergio  Whittlesee   76.116.223.149   $346.1
19      53942-299       Upton        Emig  103.190.123.125  $759.53
20      60289-247       Corri  Rockcliffe    46.150.208.18    $5.68
21      42549-609      Candra    Josowitz  158.206.200.105  $443.87
22      49999-065       Gunar        Enga     89.51.64.220   $62.60
23      52125-412  Constancia    Emberson     58.64.16.173  $666.13
24      64679-982     Felicle   Cappleman  246.127.246.202  $208.91
25      59779-556    Bartlett   Thrussell   213.80.235.219  $592.77
26      0093-1078     Wilhelm   Glanister   126.158.69.199  $722.42
27     54569-1444      Ivette     Michele      134.85.3.31  $962.30
28     59667-0024      Florie      Prewer    148.80.11.233  $565.38
29     43857-0134      Sergio  Whittlesee   76.116.223.149  $346.11
30      0378-2920    Shaylynn   Dominighi   105.104.251.83  $253.56
31     63629-3378      Leonid      Polino    68.183.173.70  $310.88
32      65862-207      Alvira      Heifer   141.170.128.72  $584.13
33      11673-003       Leroy  Stephenson     143.46.85.46  $951.73
34      60429-624     Glennis    Gianelli    48.90.168.126  $987.16
35     54973-0611       Brody      Goburn    142.230.225.8  $663.04
36     75949-1001      Madlin   Gotcliffe    45.31.218.244  $442.30
37      65862-207      Alvira      Heifer   141.170.128.72  $584.13
38      53746-191        Amil    O'Hannay     216.93.89.14  $520.86
39      42254-131   Inglebert     Houlson   102.102.146.27  $685.97
40      0904-6088         Ann     Cowling    113.27.40.144  $408.82
41      46122-023       Lloyd     Colliss     81.0.211.235  $225.69
42      0066-0508        Jedd     Hartman     21.55.247.91  $749.96
43      0456-2212      Layney    Janssens     79.49.30.228  $889.27
44      59779-276    Lynnelle     Ainslie      38.85.34.83  $473.65
45      68712-049     Phaedra     Teodoro     92.45.204.14  $445.56
46     10157-9539     Sibylla      Pedron   207.112.216.80  $362.15
47      0378-1044    Sharlene  Wolfendale   32.253.106.253  $133.98

In [5]:
x = np.array([1,2,3,4,5])
mask = np.array([False, False, True, False, True])

x[mask]

array([3, 5])

In [6]:
pair = x % 2 == 0
pair

array([False,  True, False,  True, False])

In [9]:
x[pair]

array([2, 4])

In [13]:
df[df.duplicated()]

transaction_id first_name   last_name       ip_address   amount
42      0066-0508       Jedd     Hartman     21.55.247.91  $749.96
19      53942-299      Upton        Emig  103.190.123.125  $759.53
28     59667-0024     Florie      Prewer    148.80.11.233  $565.38
20      60289-247      Corri  Rockcliffe    46.150.208.18    $5.68
32      65862-207     Alvira      Heifer   141.170.128.72  $584.13
37      65862-207     Alvira      Heifer   141.170.128.72  $584.13
15      68180-751     Marlon      Fernie   61.133.100.141  $974.30

In [14]:
duplicatas = df.duplicated(keep=False,
                           subset=["transaction_id"])

df[duplicatas].sort_values("transaction_id")

transaction_id first_name   last_name       ip_address   amount
16      0066-0508       Jedd     Hartman     21.55.247.91  $749.96
42      0066-0508       Jedd     Hartman     21.55.247.91  $749.96
5       53942-299      Upton        Emig  103.190.123.125  $759.53
19      53942-299      Upton        Emig  103.190.123.125  $759.53
2      59667-0024     Florie      Prewer    148.80.11.233  $565.38
28     59667-0024     Florie      Prewer    148.80.11.233  $565.38
7       60289-247      Corri  Rockcliffe    46.150.208.18    $5.68
20      60289-247      Corri  Rockcliffe    46.150.208.18    $5.68
14      65862-207     Alvira      Heifer   141.170.128.72  $584.13
32      65862-207     Alvira      Heifer   141.170.128.72  $584.13
37      65862-207     Alvira      Heifer   141.170.128.72  $584.13
12      68180-751     Marlon      Fernie   61.133.100.141  $974.30
15      68180-751     Marlon      Fernie   61.133.100.141  $974.30

In [16]:
df.drop_duplicates(subset=["transaction_id"], inplace=True)

In [18]:
df

transaction_id  first_name   last_name       ip_address   amount
0       50563-403      Jacobo    Haresign    18.144.134.48  $647.77
1      54569-3911     Christy        Derl  254.107.123.242  $460.47
2      59667-0024      Florie      Prewer    148.80.11.233  $565.38
3       60429-123      Danika      Shimuk   233.91.221.158  $794.76
4       0187-0771    Annelise   Antonescu   238.143.41.105  $790.41
5       53942-299       Upton        Emig  103.190.123.125  $759.53
6       41163-519     Rachael     Housley    3.188.252.248  $871.72
7       60289-247       Corri  Rockcliffe    46.150.208.18    $5.68
8       0527-1742      Ambros    Goulding   174.124.224.39  $726.12
9       57237-083        Roma     Addekin     37.14.63.174  $526.89
10      60758-060     Auberon       Boxen     168.0.223.98  $309.65
11     43857-0289      Cesare   Andriolli    244.204.3.163  $746.23
12      68180-751      Marlon      Fernie   61.133.100.141  $974.30
13      43319-040   Gavrielle      Vittet    180.20.70.166  $994.20
14      65862-207      Alvira      Heifer   141.170.128.72  $584.13
16      0066-0508        Jedd     Hartman     21.55.247.91  $749.96
17      0187-5102        Beth     Lamping    125.152.40.91   $19.07
18     44887-2589      Sergio  Whittlesee   76.116.223.149   $346.1
21      42549-609      Candra    Josowitz  158.206.200.105  $443.87
22      49999-065       Gunar        Enga     89.51.64.220   $62.60
23      52125-412  Constancia    Emberson     58.64.16.173  $666.13
24      64679-982     Felicle   Cappleman  246.127.246.202  $208.91
25      59779-556    Bartlett   Thrussell   213.80.235.219  $592.77
26      0093-1078     Wilhelm   Glanister   126.158.69.199  $722.42
27     54569-1444      Ivette     Michele      134.85.3.31  $962.30
29     43857-0134      Sergio  Whittlesee   76.116.223.149  $346.11
30      0378-2920    Shaylynn   Dominighi   105.104.251.83  $253.56
31     63629-3378      Leonid      Polino    68.183.173.70  $310.88
33      11673-003       Leroy  Stephenson     143.46.85.46  $951.73
34      60429-624     Glennis    Gianelli    48.90.168.126  $987.16
35     54973-0611       Brody      Goburn    142.230.225.8  $663.04
36     75949-1001      Madlin   Gotcliffe    45.31.218.244  $442.30
38      53746-191        Amil    O'Hannay     216.93.89.14  $520.86
39      42254-131   Inglebert     Houlson   102.102.146.27  $685.97
40      0904-6088         Ann     Cowling    113.27.40.144  $408.82
41      46122-023       Lloyd     Colliss     81.0.211.235  $225.69
43      0456-2212      Layney    Janssens     79.49.30.228  $889.27
44      59779-276    Lynnelle     Ainslie      38.85.34.83  $473.65
45      68712-049     Phaedra     Teodoro     92.45.204.14  $445.56
46     10157-9539     Sibylla      Pedron   207.112.216.80  $362.15
47      0378-1044    Sharlene  Wolfendale   32.253.106.253  $133.98