In [1]:
import numpy as np

In [4]:
ar = np.array([[1,1],[0,1]])

In [9]:
2*ar

array([[2, 2],
       [0, 2]])

In [21]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[1,1],
              [0,2]])
A+B

array([[2, 2],
       [0, 3]])

In [15]:
np.matmul(A,B)

array([[1, 3],
       [0, 2]])

In [23]:
## Axis = 0 : colonne 
A.sum(axis=0)


array([1, 2])

In [22]:
## Axis = 1 ligne
A.sum(axis=1)

array([2, 1])

In [24]:
np.array([1,2,3,4]).cumsum()

array([ 1,  3,  6, 10])

In [27]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
np.ones((2,4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [29]:
np.diag(np.array([1,4]))

array([[1, 0],
       [0, 4]])